<a href="https://colab.research.google.com/github/Oluwatosin-Ogunniyi/LITA_Capstone_Project/blob/main/File_Handling_(5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## File Handling
The key function for working with files in Python is the open() function.

The open() function takes two parameters; filename, and mode.

There are four different methods (modes) for opening a file

**"r"** - Read - Default value. Opens a file for reading, error if the file does not exist


**"a"**- Append - Opens a file for appending

**"w"** - Write - Opens a file for writing, creates the file if it does not exist

**"x"** - Create - Creates the specified file, returns an error if the file exists

Writing to a File

In [ ]:
with open("example.txt", "w") as file:
    file.write ("Hello World")

## Reading from a File

In [ ]:
#Reading frm a text file
with open ("example.txt", "r") as file :
  content = file.read()
  print (content)

Hello World
This is a new line.

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/USA_Housing.csv')
df

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,Address
0,79545.458574,5.682861,7.009188,4.09,23086.800503,1.059034e+06,"208 Michael Ferry Apt. 674\r\nLaurabury, NE 37..."
1,79248.642455,6.002900,6.730821,3.09,40173.072174,1.505891e+06,"188 Johnson Views Suite 079\r\nLake Kathleen, ..."
2,61287.067179,5.865890,8.512727,5.13,36882.159400,1.058988e+06,"9127 Elizabeth Stravenue\r\nDanieltown, WI 064..."
3,63345.240046,7.188236,5.586729,3.26,34310.242831,1.260617e+06,USS Barnett\r\nFPO AP 44820
4,59982.197226,5.040555,7.839388,4.23,26354.109472,6.309435e+05,USNS Raymond\r\nFPO AE 09386
...,...,...,...,...,...,...,...
4995,60567.944140,7.830362,6.137356,3.46,22837.361035,1.060194e+06,USNS Williams\r\nFPO AP 30153-7653
4996,78491.275435,6.999135,6.576763,4.02,25616.115489,1.482618e+06,"PSC 9258, Box 8489\r\nAPO AA 42991-3352"
4997,63390.686886,7.250591,4.805081,2.13,33266.145490,1.030730e+06,"4215 Tracy Garden Suite 076\r\nJoshualand, VA ..."
4998,68001.331235,5.534388,7.130144,5.44,42625.620156,1.198657e+06,USS Wallace\r\nFPO AE 73316
4999,65510.581804,5.992305,6.792336,4.07,46501.283803,1.298950e+06,"37778 George Ridges Apt. 509\r\nEast Holly, NV..."

## Appending to a File

In [ ]:
#Appending text file
with open ("example.txt","a") as file:
  file.write("\nThis is a new line.")

## Reading CSV Files in Python

A CSV (or Comma Separated Value) file is the most common type of file that a data scientist will ever work with. These files use a “,” as a delimiter to separate the values and each row in a CSV file is a data record.


These are useful to transfer data from one application to another and is probably the reason why they are so commonplace in the world of data science.

In [ ]:
#The Pandas library makes it very easy to read CSV files using the read_csv() function:

In [ ]:

import csv
#Writing to a csv file
with open ("data.csv", "w", newline='') as file:
  writer = csv.writer(file)
  writer.writerow(["Name","Age","City"])
  writer.writerow(["John", "25", "New York"])
  writer.writerow(["Jane", "30", "London"])

In [ ]:
# reading from a csv file

with open  ("data.csv", "r") as file:
  reader = csv.reader(file)
  for row in reader:
    print(row)

['Name', 'Age', 'City']
['John', '25', 'New York']
['Jane', '30', 'London']

In [ ]:
import pandas as pd

# read csv file into a DataFrame
df = pd.read_csv('/content/iris (1).csv')
# display DataFrame
print(df)

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

But CSV can run into problems if the values contain commas. This can be overcome by using different delimiters to separate information in the file, like ‘\t’ or ‘;’, etc. These can also be imported with the read_csv() function by specifying the delimiter in the parameter value as shown below while reading a TSV (Tab Separated Values) file:

### Working with JSON files

The json module helps to work with JSON (JavaScript Object Notation) format

In [ ]:
import json
#from json import dump,load
#writing dictionary to a json file
data = {"name": "John","age": 25, "city": "New York"}

with open("data.json","w") as file:
  json.dump(data,file)

In [ ]:
# Reading from a json file
with open("data.json","r") as file:
  data = json.load(file)
  print(data)

{'name': 'John', 'age': 25, 'city': 'New York'}

## Reading and Loading from G drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
file_path=

In [ ]:
df=pd.read_csv(file_path)
df

,Name,Nationality,Current Rank,Previous Year Rank,Sport,Year,earnings ($ million)
0,Mike Tyson,USA,1,Not Listed,Boxing,1990,28.6
1,Buster Douglas,USA,2,Not Listed,Boxing,1990,26.0
2,Sugar Ray Leonard,USA,3,Not Listed,Boxing,1990,13.0
3,Ayrton Senna,Brazil,4,Not Listed,Auto Racing,1990,10.0
4,Alain Prost,France,5,Not Listed,Auto Racing,1990,9.0
...,...,...,...,...,...,...,...
286,Russell Wilson,USA,6,Not Listed,American Football,2019,89.5
287,Aaron Rogers,USA,7,Not Listed,American Football,2019,89.3
288,LeBron James,USA,8,6,Basketball,2019,89.0
289,Stephen Curry,USA,9,8,Basketball,2019,79.8
290,Kevin Durant,USA,10,>10,Basketball,2019,65.4

In [ ]:
df.shape

(291, 7)

In [ ]:
df.head(13)

,Name,Nationality,Current Rank,Previous Year Rank,Sport,Year,earnings ($ million)
0,Mike Tyson,USA,1,Not Listed,Boxing,1990,28.6
1,Buster Douglas,USA,2,Not Listed,Boxing,1990,26.0
2,Sugar Ray Leonard,USA,3,Not Listed,Boxing,1990,13.0
3,Ayrton Senna,Brazil,4,Not Listed,Auto Racing,1990,10.0
4,Alain Prost,France,5,Not Listed,Auto Racing,1990,9.0
5,Jack Nicklaus,USA,6,Not Listed,Golf,1990,8.6
6,Greg Norman,Australia,7,Not Listed,Golf,1990,8.5
7,Michael Jordan,USA,8,Not Listed,Basketball,1990,8.1
8,Arnold Palmer,USA,8,Not Listed,Golf,1990,8.1
9,Evander Holyfield,USA,8,Not Listed,Boxing,1990,8.1
10,Evander Holyfield,USA,1,8,Boxing,1991,60.5
11,Mike Tyson,USA,2,1,Boxing,1991,31.5
12,Michael Jordan,USA,3,8,Basketball,1991,16.0

In [ ]:
df.tail()

,Name,Nationality,Current Rank,Previous Year Rank,Sport,Year,earnings ($ million)
286,Russell Wilson,USA,6,Not Listed,American Football,2019,89.5
287,Aaron Rogers,USA,7,Not Listed,American Football,2019,89.3
288,LeBron James,USA,8,6,Basketball,2019,89.0
289,Stephen Curry,USA,9,8,Basketball,2019,79.8
290,Kevin Durant,USA,10,>10,Basketball,2019,65.4

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 291 entries, 0 to 290
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Name                  291 non-null    object
 1   Nationality           291 non-null    object
 2   Current Rank          291 non-null    int64
 3   Previous Year Rank    291 non-null    object
 4   Sport                 291 non-null    object
 5   Year                  291 non-null    int64
 6   earnings ($ million)  291 non-null    float64
dtypes: float64(1), int64(2), object(4)
memory usage: 16.0+ KB

In [ ]:
df.max()

Name                    Wayne Gretzky
Nationality                       USA
Current Rank                       10
Previous Year Rank         Not Listed
Sport                   motorcycle gp
Year                             2019
earnings ($ million)            300.0
dtype: object

In [ ]:
df['Sport'].unique()

array(['Boxing', 'Auto Racing', 'Golf', 'Basketball', 'Tennis',
       'American Football', 'Baseball', 'Ice Hockey',
       'American Football / Baseball', 'F1 racing', 'Soccer', 'cycling',
       'motorcycle gp', 'MMA'], dtype=object)

In [ ]:
df.drop('Name',axis=1)

,Nationality,Current Rank,Previous Year Rank,Sport,Year,earnings ($ million)
0,USA,1,Not Listed,Boxing,1990,28.6
1,USA,2,Not Listed,Boxing,1990,26.0
2,USA,3,Not Listed,Boxing,1990,13.0
3,Brazil,4,Not Listed,Auto Racing,1990,10.0
4,France,5,Not Listed,Auto Racing,1990,9.0
...,...,...,...,...,...,...
286,USA,6,Not Listed,American Football,2019,89.5
287,USA,7,Not Listed,American Football,2019,89.3
288,USA,8,6,Basketball,2019,89.0
289,USA,9,8,Basketball,2019,79.8
290,USA,10,>10,Basketball,2019,65.4

In [ ]:
df.drop(200,axis=0)

,Name,Nationality,Current Rank,Previous Year Rank,Sport,Year,earnings ($ million)
0,Mike Tyson,USA,1,Not Listed,Boxing,1990,28.6
1,Buster Douglas,USA,2,Not Listed,Boxing,1990,26.0
2,Sugar Ray Leonard,USA,3,Not Listed,Boxing,1990,13.0
3,Ayrton Senna,Brazil,4,Not Listed,Auto Racing,1990,10.0
4,Alain Prost,France,5,Not Listed,Auto Racing,1990,9.0
...,...,...,...,...,...,...,...
286,Russell Wilson,USA,6,Not Listed,American Football,2019,89.5
287,Aaron Rogers,USA,7,Not Listed,American Football,2019,89.3
288,LeBron James,USA,8,6,Basketball,2019,89.0
289,Stephen Curry,USA,9,8,Basketball,2019,79.8
290,Kevin Durant,USA,10,>10,Basketball,2019,65.4

looks like this daaset has data types of object, int, float

In [ ]:
#json file
file_path='/content/drive/MyDrive/Unsup.PROJECT/Car-Attributes.json'

In [ ]:
DataFrame=pd.read_json(file_path)

## Using statement for Resource Management


The with statement automatically closes files when done, this is considered best practice to avoid leaving files open , which oculd leads to resource leaks.

In [ ]:
with open("data.csv","r") as file:
  content = file.read()
  print(content)
  # the file is automatically closed after this block, no need to manually close it

Name,Age,City
John,25,New York
Jane,30,London

In [ ]:
file = open("data.csv","r")
content = file.read()
file.close() #you must remember to close the file

## Importing and Using Python Modules in Python

### What Are Python Modules?
A module is a file containing Python definitions and statements (like functions, classes, and variables) that can be reused in other programs.
Python modules allow you to organize your code into smaller, more manageable files and reuse code across multiple projects.


## *Types of Modules in Python*
*Built-in Modules:*

Pre-installed modules that come with Python.

Examples: math, os, random, sys,

*External/Third-Party Modules:*

Modules installed via a package manager like pip.

Examples: numpy, pandas, matplotlib.

### Import an entire module:

In [ ]:
import math
print(math.sqrt(16))

4.0

### 2. Import With Alias

Use an alias to shorten the module name:

In [ ]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]

### 3. Import Specific Functions or Attributes

import only the required functions:

In [ ]:
from math import sqrt, pi
print(sqrt(16))
print(pi)

4.0
3.141592653589793

### 4. Import All Functions
Import everything from a module:

In [ ]:
from math import *
print(cos(0))
#Note: Avoid using this unless necessary, as it can cause naming conflicts.

1.0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
file_path= '/content/drive/MyDrive/usedcars.csv'

In [ ]:
df=pd.read_csv(file_path)

In [ ]:
df

     year model  price  mileage   color transmission
0    2011   SEL  21992     7413    Gray         AUTO
1    2011   SEL  20995    10926    Gray         AUTO
2    2011   SEL  19995     7351  Silver         AUTO
3    2011   SEL  17809    11613    Gray         AUTO
4    2011    SE  17500     8367   White         AUTO
..    ...   ...    ...      ...     ...          ...
145  2006   SES   6200    95000  Silver         AUTO
146  2006    SE   5995    87003     Red         AUTO
147  2006    SE   5980    96841     Red         AUTO
148  2006    SE   4899   151479    Gray         AUTO
149  2006    SE   3800   109259     Red         AUTO

[150 rows x 6 columns]

In [ ]:
df.head()

   year model  price  mileage   color transmission
0  2011   SEL  21992     7413    Gray         AUTO
1  2011   SEL  20995    10926    Gray         AUTO
2  2011   SEL  19995     7351  Silver         AUTO
3  2011   SEL  17809    11613    Gray         AUTO
4  2011    SE  17500     8367   White         AUTO